import {suggestInteriorPlacement} from '../../packages/geometry/placement.js';
import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Button,NumberField,Label,Group,Input,TextField,ModalOverlay,Modal,Dialog,Heading,I18nProvider} from 'react-aria-components';
import {CommandSession} from '../../packages/commands/index.js';
import {emptyProject} from '../../packages/model/room.js';
import {saveRecovery,recover,exportProject,importProject,libraryProducts} from '../../packages/persistence/index.js';
import {inspectRepository,installPlugin,installedPlugins,removePlugin} from '../../packages/plugins/index.js';
import {importProductUrl} from '../../packages/catalog/index.js';
import {i18next} from '../../packages/localization/index.js';
import {Plan} from '../../packages/view2d/Plan.jsx';
import {Scene} from '../../packages/view3d/Scene.jsx';
import './style.css';
function Num({label,value,onChange,min}){return <NumberField value={value??NaN} onChange={onChange} minValue={min} formatOptions={{maximumFractionDigits:8}}><Label>{label}</Label><Group><Button slot="decrement" aria-label={`${label} -`}>−</Button><Input/><Button slot="increment" aria-label={`${label} +`}>+</Button></Group></NumberField>;}
function App(){
 const [repository,setRepository]=useState('https://github.com/yaniv-golan/RUMSYN-ikea-israel'),[plugins,setPlugins]=useState([]),[pluginCandidate,setPluginCandidate]=useState(null),[pluginBusy,setPluginBusy]=useState(false);
 const [tool,setTool]=useState('room'),[librarySearch,setLibrarySearch]=useState('');const propertiesPanel=useRef(null),focusProperties=useRef(false);
 const [upgradeNotice,setUpgradeNotice]=useState(false);
 const cameraMemory=useRef(null);
 const [cutaway,setCutaway]=useState(true),[fitRequest,setFitRequest]=useState(0),[zoomRequest,setZoomRequest]=useState(0);
 const [lang,setLang]=useState('en'),t=k=>i18next.t(k,{lng:lang});
 const [session,setSession]=useState(()=>new CommandSession(emptyProject(crypto.randomUUID()))),[state,setState]=useState(session.state),[ready,setReady]=useState(false),[blocked,setBlocked]=useState(false),[view,setView]=useState('2d'),[selected,setSelected]=useState(null),[pending,setPending]=useState(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[library,setLibrary]=useState([]);
 const [measure,setMeasure]=useState({sides:[undefined,undefined,undefined,undefined],diagonal:undefined,height:240,thickness:15,orientation:''});
 const [opening,setOpening]=useState({width:90,height:200,offset:30});const [furniture,setFurniture]=useState({category:'table',width:100,depth:60,height:75,x:100,y:100,elevation:0,rotation:0});const [url,setUrl]=useState('');const [edit,setEdit]=useState({});
 const selectedWall=state.walls.find(w=>w.id===selected),selectedFurniture=state.furniture?.find(f=>f.id===selected),selectedOpening=state.attachments.find(o=>o.id===selected);
 useEffect(()=>{installedPlugins().then(setPlugins).catch(e=>setError(e.message));},[]);
 useEffect(()=>{let active=true;recover().then(s=>{if(!active)return;if(s){setSession(s);setState(structuredClone(s.state));setUpgradeNotice(s.importedVersion===1);setStatus('recovered');}setReady(true);}).catch(e=>{if(active){setError(e.message);setBlocked(true);setReady(true);}});libraryProducts().then(setLibrary).catch(e=>setError(e.message));return()=>{active=false;};},[]);
 useEffect(()=>{if(!ready||blocked)return;let current=true;saveRecovery(session).then(()=>current&&setStatus('local')).catch(e=>{if(current){setStatus('unsaved');setError(e.message);}});return()=>{current=false;};},[state,ready,blocked,session]);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';},[lang]);
 useEffect(()=>{setEdit(selectedWall?{length:selectedWall.length.value}:selectedFurniture?{width:selectedFurniture.width,depth:selectedFurniture.depth,height:selectedFurniture.height,x:selectedFurniture.x,y:selectedFurniture.y,elevation:selectedFurniture.elevation,rotation:selectedFurniture.rotation}:{});},[selected,state]);
 const selectObject=id=>{setSelected(id);setTool('properties');focusProperties.current=true;};
 useEffect(()=>{if(tool==='properties'&&focusProperties.current){propertiesPanel.current?.querySelector('h2')?.focus({preventScroll:true});focusProperties.current=false;}},[tool,selected]);
 const refresh=()=>setState(structuredClone(session.state));
 const attempt=fn=>{setError('');try{fn();}catch(e){setError(e.message);}};
 const preview=fn=>attempt(()=>{if(pending)session.cancel(pending.id);setPending(fn());});
 const cancel=()=>{if(pending)session.cancel(pending.id);setPending(null);};
 const apply=()=>attempt(()=>{const firstRoom=!state.room&&pending.after.room;session.apply(pending.id);if(firstRoom){try{setFurniture(f=>({...f,...suggestInteriorPlacement(session.state,f)}));}catch{}}setPending(null);refresh();});
 const newProject=()=>{cameraMemory.current=null;cancel();const s=new CommandSession(emptyProject(crypto.randomUUID()));setSession(s);setState(s.state);setSelected(null);setTool('room');setBlocked(false);setUpgradeNotice(false);setError('');};
 const save=()=>attempt(()=>{const bytes=exportProject(session),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:'application/zip'}));a.download='room.rumsyn';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
 const open=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5_000_000)throw new Error('Project exceeds 5 MB compressed limit');const s=importProject(new Uint8Array(await file.arrayBuffer()));cancel();setSession(s);setState(structuredClone(s.state));setSelected(null);setTool('room');setBlocked(false);setError('');setUpgradeNotice(s.importedVersion===1);}catch(e){setError(e.message);}finally{e.target.value='';}};
 const addFurniture=(product)=>preview(()=>session.previewFurniture({id:crypto.randomUUID(),...furniture,...(product?{category:'table',width:product.dimensions.width,depth:product.dimensions.depth,height:product.dimensions.height,product}:{} )}));
 const visible=pending?.after??state;
 return <I18nProvider locale={lang==='he'?'he-IL':'en-US'}><div className="app-shell"><a className="skip-link" href="#tools">{t('skipTools')}</a><a className="skip-link" href="#workspace">{t('skipScene')}</a>
  <header><div><div className="brand">RUM<span>SYN</span></div><p>{t('intro')}</p></div><div className="header-controls"><label>{t('language')}<select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="he">עברית</option></select></label><Button onPress={newProject} isDisabled={!ready}>{t('newProject')}</Button><Button onPress={save} aria-description={t('saveCompatibility')} isDisabled={!ready}>{t('save')}</Button><label className="file-button">{t('open')}<input type="file" accept=".rumsyn,.zip" onChange={open} aria-label={t('open')}/></label></div></header>
  <div className="preview-notice">{t('previewBuild')}</div>
  <main><aside className="sidebar" id="tools"><nav className="tool-modes" aria-label={t('toolModes')}>{['room','furnish','properties'].map(k=><Button key={k} aria-pressed={tool===k} onPress={()=>setTool(k)}>{t(k==='room'?'roomMode':k==='furnish'?'furnishMode':'propertiesMode')}</Button>)}</nav><div className="task-panel">
   {tool==='room'&&(!state.room?<section><h1>{t('measure')}</h1><p className="help">{t('needMeasurements')}</p>{measure.sides.map((value,i)=><Num key={i} label={`${t('wall')} ${String.fromCharCode(65+i)} (cm)`} value={value} onChange={v=>setMeasure(m=>({...m,sides:m.sides.map((x,j)=>i===j?v:x)}))} min={1}/>)}<Num label={t('diagonal')} value={measure.diagonal} min={1} onChange={v=>setMeasure(m=>({...m,diagonal:v}))}/><Num label={t('height')} value={measure.height} min={1} onChange={v=>setMeasure(m=>({...m,height:v}))}/><Num label={t('thickness')} value={measure.thickness} min={1} onChange={v=>setMeasure(m=>({...m,thickness:v}))}/><label>{t('orientation')}<select value={measure.orientation} onChange={e=>setMeasure(m=>({...m,orientation:e.target.value}))}><option value="">—</option><option value="clockwise">↻</option><option value="counterclockwise">↺</option></select></label><Button className="primary" onPress={()=>preview(()=>session.previewRoom(measure))}>{t('create')}</Button></section>:<section><h2>{t('objects')}</h2><ul className="object-list">{[...state.walls,...state.attachments,...(state.furniture??[])].map(o=><li key={o.id}><Button aria-pressed={o.id===selected} onPress={()=>selectObject(o.id)}>{o.name??o.product?.name??(o.category?t(o.category):t('opening'))}{o.length?` · ${o.length.value.toFixed(2)} cm`:''}</Button></li>)}</ul></section>)}
   {tool==='properties'&&<section ref={propertiesPanel}><h2 tabIndex={-1}>{t('properties')}</h2>{selectedWall?<><Num label={t('length')} value={edit.length} min={1} onChange={v=>setEdit({length:v})}/><p className="help">{selectedWall.length.source} · {selectedWall.id}</p><Button onPress={()=>preview(()=>session.previewWallLength(selectedWall.id,edit.length))}>{t('preview')}</Button><h3>{t('opening')}</h3>{['width','height','offset'].map(k=><Num key={k} label={t(k==='height'?'itemHeight':k)} value={opening[k]} min={k==='offset'?0:1} onChange={v=>setOpening(o=>({...o,[k]:v}))}/>)}<Button onPress={()=>preview(()=>session.previewOpening({id:crypto.randomUUID(),wallId:selectedWall.id,...opening,bottom:0,anchor:'start'}))}>{t('add')}</Button></>:selectedFurniture?<>{(selectedFurniture.product?['x','y','elevation','rotation']:['width','depth','height','x','y','elevation','rotation']).map(k=><Num key={k} label={t(k==='height'?'itemHeight':k)} value={edit[k]} min={['width','depth','height'].includes(k)?1:undefined} onChange={v=>setEdit(o=>({...o,[k]:v}))}/>)}<Button onPress={()=>preview(()=>session.previewFurnitureEdit(selectedFurniture.id,edit))}>{t('preview')}</Button>{selectedFurniture.product&&<p>{t('generic')} · {selectedFurniture.width} × {selectedFurniture.depth} × {selectedFurniture.height} cm · {t('productSizeFixed')}</p>}</>:selectedOpening?<p>{selectedOpening.width} × {selectedOpening.height} cm · {selectedOpening.offset} cm</p>:<p className="help">{t('choose')}</p>}</section>}
   {tool==='furnish'&&<>
   {state.room&&<section><h2>{t('furniture')}</h2><label>{t('category')}<select value={furniture.category} onChange={e=>setFurniture(f=>({...f,category:e.target.value}))}>{['table','chair','cabinet'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label>{['width','depth','height','x','y'].map(k=><Num key={k} label={t(k==='height'?'itemHeight':k)} value={furniture[k]} min={['x','y'].includes(k)?undefined:1} onChange={v=>setFurniture(f=>({...f,[k]:v}))}/>)}<Button onPress={()=>addFurniture()}>{t('add')}</Button></section>}
   <section><h2>{t('plugins')}</h2><TextField value={repository} onChange={setRepository}><Label>{t('repository')}</Label><Input dir="ltr"/></TextField><Button isDisabled={pluginBusy} onPress={async()=>{setPluginBusy(true);setError('');try{setPluginCandidate(await inspectRepository(repository));}catch(e){setError(e.message);}finally{setPluginBusy(false);}}}>{t('inspectPlugin')}</Button>{pluginCandidate&&<article className="product-card"><h3>{t('reviewPlugin')}</h3><p dir="auto">{pluginCandidate.repository}</p><p>{t('publisher')}: {pluginCandidate.manifest.publisher}</p><p>{pluginCandidate.manifest.id} · {pluginCandidate.manifest.country} · {pluginCandidate.manifest.catalog.version}</p><p dir="ltr">{pluginCandidate.manifest.origins.join(', ')}</p><p>{t('pluginTrust')}</p><Button onPress={()=>setPluginCandidate(null)}>{t('cancel')}</Button><Button onPress={async()=>{try{await installPlugin(pluginCandidate);setPlugins(await installedPlugins());setPluginCandidate(null);}catch(e){setError(e.message);}}}>{t('installPlugin')}</Button></article>}{plugins.map(p=><article className="product-card" key={p.id}><strong>{p.id}</strong><p>{p.manifest.country} · {p.manifest.catalog.version}</p><a href={p.repository} target="_blank" rel="noreferrer">{t('repository')}</a><Button onPress={async()=>{try{await removePlugin(p.id);setPlugins(await installedPlugins());}catch(e){setError(e.message);}}}>{t('removePlugin')}</Button><p>{t('removeKeepsProducts')}</p></article>)}</section>
   <section><h2>{t('library')}</h2><p className="help">{t('importLimit')}</p><TextField value={url} onChange={setUrl}><Label>{t('url')}</Label><Input dir="ltr"/></TextField><Button onPress={async()=>{try{setError('');await importProductUrl(url);setLibrary(await libraryProducts());}catch(e){setError(e.message);}}}>{t('import')}</Button><TextField value={librarySearch} onChange={setLibrarySearch}><Label>{t('searchLibrary')}</Label><Input/></TextField>{library.filter(p=>`${p.name} ${p.article}`.toLocaleLowerCase().includes(librarySearch.toLocaleLowerCase())).map(p=><article className="product-card" key={p.identity}><strong dir="auto">{p.name}</strong><p>{p.dimensions.width} × {p.dimensions.depth} × {p.dimensions.height} cm</p><p>{t('generic')}</p><p>{t('price')}: {p.price??'—'} {p.currency} · {p.retrieved}</p><a href={p.sourceUrl} target="_blank" rel="noreferrer">{t('source')}</a> <Button isDisabled={!state.room} onPress={()=>addFurniture(p)}>{t('place')}</Button></article>)}</section></>}
  </div></aside><section className="workspace" id="workspace" tabIndex={-1}><div className="view-toolbar"><div><Button aria-pressed={view==='2d'} onPress={()=>setView('2d')}>{t('plan')}</Button><Button aria-pressed={view==='3d'} onPress={()=>setView('3d')}>{t('space')}</Button></div><div><Button isDisabled={session.cursor===0||Boolean(pending)} onPress={()=>{session.undo();refresh();}}>{t('undo')}</Button><Button isDisabled={session.cursor===session.history.length||Boolean(pending)} onPress={()=>{session.redo();refresh();}}>{t('redo')}</Button></div></div>{view==='3d'&&visible.room&&<div className="scene-controls"><Button onPress={()=>setCutaway(v=>!v)}>{t(cutaway?'showWalls':'cutaway')}</Button><Button onPress={()=>setFitRequest(v=>v+1)}>{t('fitView')}</Button><Button onPress={()=>setZoomRequest(v=>v+1)}>{t('zoomIn')}</Button><Button onPress={()=>setZoomRequest(v=>v-1)}>{t('zoomOut')}</Button><span>{t('viewOnly')}</span></div>}<div className="canvas-wrap">{!visible.room?<div className="empty-canvas"><div className="empty-symbol">⌑</div><p>{t('empty')}</p></div>:view==='2d'?<Plan state={visible} selected={selected} onSelect={selectObject} label={t('plan')}/>:<Scene zoomRequest={zoomRequest} cutaway={cutaway} fitRequest={fitRequest} cameraMemory={cameraMemory} state={visible} selected={selected} onSelect={selectObject} label={t('space')}/>}</div><div className="status" aria-live="polite">{upgradeNotice&&<p>{t('upgraded')}</p>}{status&&t(status)}</div>{error&&<div className="error" role="alert">{error}</div>}</section></main>
  <ModalOverlay isOpen={Boolean(pending)} onOpenChange={open=>!open&&cancel()} isDismissable><Modal><Dialog><Heading slot="title">{t('changes')}</Heading>{pending?.changes.map((change,i)=><p key={i}>{change.oldValue!==undefined?`${change.wallId}: ${change.oldValue.toFixed(2)} → ${change.newValue.toFixed(2)} cm`:t(pending?.after.room&&!state.room?'measure':'add')}</p>)}{pending?.affected.length>0&&<p>{t('opening')}: {pending.affected.length}</p>}{pending?.warnings?.map(w=><p className="error" key={w}>{w}</p>)}<div className="dialog-actions"><Button onPress={cancel}>{t('cancel')}</Button><Button className="primary" onPress={apply}>{t('apply')}</Button></div></Dialog></Modal></ModalOverlay>
 </div></I18nProvider>;
}
createRoot(document.getElementById('root')).render(<App/>);
