import {MeasurementContext} from './LengthField.jsx';
import {formatMeasurement} from '../../packages/model/units.js';
import React,{useState,useEffect,useContext} from 'react';
import {Button} from 'react-aria-components';
export function presetPoints(draft){const {width:w,depth:d,cutWidth:cw,cutDepth:cd,preset}=draft;if(![w,d].every(v=>Number.isFinite(v)&&v>0)||preset==='L'&&![cw,cd].every((v,i)=>Number.isFinite(v)&&v>0&&v<(i?d:w)))throw new Error('Preset dimensions and notch must fit the proposed outline');return preset==='rectangle'?[[0,0],[w,0],[w,d],[0,d]]:[[0,0],[w,0],[w,d-cd],[w-cw,d-cd],[w-cw,d],[0,d]];}
export function OutlineEntry({entry,draft,setDraft,Num,t,height,thickness,setMeasure,onPreview}){
 const {unit}=useContext(MeasurementContext);
 const change=(key,value)=>setDraft(d=>({...d,[key]:value}));
 return <section><h1>{t(entry==='preset'?'presetEntry':entry==='draw'?'drawEntry':'perimeterEntry')}</h1><p className="help">{t(entry==='perimeter'?'perimeterHelp':'approximateShape')}</p><p className="help">{t('measurementHelp')}</p>
 {entry==='preset'?<><fieldset className="preset-choices"><legend>{t('shape')}</legend>{['L','rectangle'].map(shape=><label key={shape} className="preset-card"><input type="radio" name="outline-preset" checked={draft.preset===shape} onChange={()=>change('preset',shape)}/><svg viewBox="0 0 100 85" aria-hidden="true"><path d={shape==='L'?'M15 10H85V40H50V75H15Z':'M15 10H85V75H15Z'} fill="none" stroke="currentColor" strokeWidth="5"/></svg><span>{t(shape==='L'?'lShape':'rectangleShape')}</span></label>)}</fieldset>{['width','depth',...(draft.preset==='L'?['cutWidth','cutDepth']:[])].map(k=><Num key={k} label={t(k)} value={draft[k]} min={1} onChange={v=>change(k,v)}/>)}</>:entry==='draw'?<><p className="help">{unit==='imperial'?t('drawHelp').replace(/25 (?:cm|ס״מ)/,formatMeasurement(25,unit)):t('drawHelp')}</p>{draft.points.map((p,i)=><fieldset key={i}><legend>{t('corner')} {i+1}</legend>{['x','y'].map((key,j)=><Num key={key} label={`${t(key)} · ${t('corner')} ${i+1}`} value={p[j]} onChange={v=>setDraft(d=>({...d,points:d.points.map((q,n)=>n===i?q.map((x,m)=>m===j?v:x):q)}))}/>)}<Button onPress={()=>setDraft(d=>({...d,points:d.points.filter((p,n)=>n!==i)}))}>{t('removeCorner')}</Button></fieldset>)}<Button onPress={()=>setDraft(d=>({...d,points:[...d.points,[0,0]]}))}>{t('addCorner')}</Button></>:<>{draft.segments.map((segment,i)=><fieldset key={i}><legend>{t('wall')} {String.fromCharCode(65+i)}</legend><Num label={`${t('length')} · ${String.fromCharCode(65+i)}`} value={segment.length} min={1} onChange={v=>setDraft(d=>({...d,segments:d.segments.map((s,n)=>n===i?{...s,length:v}:s)}))}/><Num angle label={`${t('direction')} · ${String.fromCharCode(65+i)}`} value={segment.direction} onChange={v=>setDraft(d=>({...d,segments:d.segments.map((s,n)=>n===i?{...s,direction:v}:s)}))}/><Button onPress={()=>setDraft(d=>({...d,segments:d.segments.filter((s,n)=>n!==i)}))}>{t('removeWall')}</Button></fieldset>)}<Button onPress={()=>setDraft(d=>({...d,segments:[...d.segments,{}]}))}>{t('addWall')}</Button></>}
 <Num label={t('height')} value={height} min={1} onChange={v=>setMeasure(m=>({...m,height:v}))}/><Num label={t('thickness')} value={thickness} min={1} onChange={v=>setMeasure(m=>({...m,thickness:v}))}/><Button className="primary" onPress={onPreview}>{t('previewOutline')}</Button></section>;
}
export function DraftCanvas({points,onPoint,t}){const {unit}=useContext(MeasurementContext);const [bounds,setBounds]=useState([-50,-550,600,600]);const fit=()=>{if(!points.length)return;const xs=points.map(p=>p[0]),ys=points.map(p=>-p[1]),span=Math.max(100,Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys)),padding=span*.12;setBounds([Math.min(...xs)-padding,Math.min(...ys)-padding,Math.max(...xs)-Math.min(...xs)+2*padding,Math.max(...ys)-Math.min(...ys)+2*padding]);};useEffect(()=>{if(!onPoint)fit();},[points.map(p=>p.join(',')).join(';')]);return <div className="draft-canvas-wrap"><Button onPress={fit}>{t('fitDraft')}</Button> <svg className="plan draft-plan" viewBox={bounds.join(' ')} role="img" aria-label={t('draftOutline')} onPointerDown={event=>{if(!onPoint)return;const svg=event.currentTarget,p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());onPoint([Math.round(q.x/25)*25,Math.round(-q.y/25)*25]);}}><polyline points={points.map(([x,y])=>`${x},${-y}`).join(' ')} fill="none" stroke="#465463" strokeWidth="3"/>{points.length>2&&<line x1={points.at(-1)[0]} y1={-points.at(-1)[1]} x2={points[0][0]} y2={-points[0][1]} stroke="#465463" strokeDasharray="7 5"/>}{points.map(([x,y],i)=><g key={i}><circle cx={x} cy={-y} r={Math.max(bounds[2],bounds[3])*.012} fill="#e46c45"/><text style={{fontSize:Math.max(bounds[2],bounds[3])*.025}} x={x+12} y={-y-12}>{t('corner')} {i+1}</text></g>)}</svg><p className="draft-caption">{t('draftOnly')} · {t(unit==='metric'?'metric':'imperial')}</p></div>;}
