import Ajv from 'ajv';
import {sha256,validateCatalog} from '../catalog/index.js';
import {db} from '../persistence/index.js';
export const pluginSchema={type:'object',additionalProperties:false,required:['contractVersion','id','publisher','country','compatibility','origins','catalog'],properties:{contractVersion:{const:1},id:{type:'string',pattern:'^[a-z0-9-]{1,80}$'},publisher:{type:'string',minLength:1,maxLength:200},country:{const:'IL'},compatibility:{type:'object',additionalProperties:false,required:['catalogSchema'],properties:{catalogSchema:{const:1}}},origins:{type:'array',minItems:1,maxItems:5,uniqueItems:true,items:{type:'string',maxLength:200}},catalog:{type:'object',additionalProperties:false,required:['version','url','sha256'],properties:{version:{type:'string',pattern:'^[a-zA-Z0-9.-]{1,80}$'},url:{type:'string',maxLength:2000},sha256:{type:'string',pattern:'^[a-f0-9]{64}$'}}}}};
const validate=new Ajv({coerceTypes:false,removeAdditional:false}).compile(pluginSchema);
export function repositoryIdentity(input){let u;try{u=new URL(input);}catch{throw new Error('Enter a public GitHub repository URL');}if(u.origin!=='https://github.com'||u.search||u.hash||!/^\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/?$/.test(u.pathname))throw new Error('Enter a public GitHub repository URL');const [owner,repo]=u.pathname.split('/').filter(Boolean);return {owner,repo,repository:`https://github.com/${owner}/${repo}`};}
export function validatePlugin(value,owner){if(!validate(value))throw new Error('Unsupported plugin contract');const allowed=`https://${owner.toLowerCase()}.github.io`;for(const origin of value.origins)if(origin!==allowed)throw new Error('Plugin origin must be the repository owner’s GitHub Pages origin');let u;try{u=new URL(value.catalog.url);}catch{throw new Error('Invalid catalog URL');}if(u.username||u.password||u.search||u.hash||!value.origins.includes(u.origin)||!u.pathname.includes(`/${value.catalog.version}/`))throw new Error('Catalog must use a declared immutable version path');return value;}
export async function fetchBounded(url,limit,fetcher=fetch){const response=await fetcher(url,{redirect:'error',credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok||response.redirected||response.url&&response.url!==url)throw new Error('Plugin resource unavailable or redirected');if(Number(response.headers.get('content-length'))>limit)throw new Error('Plugin resource exceeds size limit');if(!response.body)throw new Error('Plugin response has no body');const reader=response.body.getReader(),chunks=[];let size=0;try{for(;;){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit)throw new Error('Plugin resource exceeds size limit');chunks.push(value);}}finally{await reader.cancel();}const bytes=new Uint8Array(size);let at=0;for(const chunk of chunks){bytes.set(chunk,at);at+=chunk.byteLength;}return bytes;}
const decode=bytes=>JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));
export async function inspectRepository(input,{fetcher=fetch}={}){
 const identity=repositoryIdentity(input),base=`https://api.github.com/repos/${identity.owner}/${identity.repo}`,metadata=decode(await fetchBounded(base,256000,fetcher));if(metadata.private!==false||typeof metadata.default_branch!=='string')throw new Error('Repository must be public');const ref=decode(await fetchBounded(`${base}/commits/${encodeURIComponent(metadata.default_branch)}`,256000,fetcher));if(!/^[a-f0-9]{40}$/.test(ref.sha))throw new Error('Repository commit unavailable');
 const manifestUrl=`https://raw.githubusercontent.com/${identity.owner}/${identity.repo}/${ref.sha}/rum-plugin.json`,manifestBytes=await fetchBounded(manifestUrl,32000,fetcher),manifest=validatePlugin(decode(manifestBytes),identity.owner);
 const catalogBytes=await fetchBounded(manifest.catalog.url,2000000,fetcher);if(await sha256(catalogBytes)!==manifest.catalog.sha256)throw new Error('Catalog content hash mismatch');const catalog=validateCatalog(decode(catalogBytes));if(catalog.version!==manifest.catalog.version||catalog.country!==manifest.country)throw new Error('Catalog identity/version mismatch');
 return {...identity,id:manifest.id,commit:ref.sha,manifestUrl,manifestHash:await sha256(manifestBytes),manifestText:new TextDecoder('utf-8',{fatal:true}).decode(manifestBytes),manifest,catalogText:new TextDecoder().decode(catalogBytes)};
}
export async function installPlugin(candidate){await catalogFromInstalled(candidate);await db().plugins.put(structuredClone(candidate));}
export async function installedPlugins(){return db().plugins.toArray();}
export async function removePlugin(id){await db().plugins.delete(id);}
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));return value;}
export async function catalogFromInstalled(plugin){if(typeof plugin.manifestText!=='string'||await sha256(new TextEncoder().encode(plugin.manifestText))!==plugin.manifestHash)throw new Error('Manifest cache hash mismatch; saved products remain unchanged');const accepted=validatePlugin(JSON.parse(plugin.manifestText),plugin.owner);validatePlugin(plugin.manifest,plugin.owner);if(JSON.stringify(canonical(accepted))!==JSON.stringify(canonical(plugin.manifest)))throw new Error('Manifest cache disagrees with accepted bytes');if(await sha256(new TextEncoder().encode(plugin.catalogText))!==plugin.manifest.catalog.sha256)throw new Error('Catalog cache hash mismatch; saved products remain unchanged');const record=validateCatalog(JSON.parse(plugin.catalogText));if(record.version!==plugin.manifest.catalog.version)throw new Error('Catalog cache version mismatch');return {record,hash:plugin.manifest.catalog.sha256,plugin:{id:plugin.id,repository:plugin.repository,commit:plugin.commit,manifestHash:plugin.manifestHash}};}
