const EPS=1e-6;
export function topologyPoints(room){return room.corners.map(c=>[c.x,c.y]);}
export function edgeEnds(room,edge){const start=room.corners.find(c=>c.id===edge.startCornerId),end=room.corners.find(c=>c.id===edge.endCornerId);if(!start||!end)throw new Error('Unknown topology corner');return [[start.x,start.y],[end.x,end.y]];}
export function edgeLength(room,edge){const [a,b]=edgeEnds(room,edge);if(edge.kind==='line')return Math.hypot(b[0]-a[0],b[1]-a[1]);if(edge.kind!=='arc'||!Array.isArray(edge.centre)||edge.centre.length!==2||!edge.centre.every(Number.isFinite)||!Number.isFinite(edge.sweep)||Math.abs(edge.sweep)<=EPS||Math.abs(edge.sweep)>=2*Math.PI)throw new Error('Invalid arc parameters');const [cx,cy]=edge.centre,r=Math.hypot(a[0]-cx,a[1]-cy),t=Math.atan2(a[1]-cy,a[0]-cx)+edge.sweep;if(r<=EPS||Math.hypot(cx+r*Math.cos(t)-b[0],cy+r*Math.sin(t)-b[1])>EPS)throw new Error('Arc endpoint disagrees with sweep');return r*Math.abs(edge.sweep);}
export function pointAtEdge(room,edge,distance){const length=edgeLength(room,edge);if(!Number.isFinite(distance)||distance<0||distance>length)throw new Error('Host offset outside edge');const [a,b]=edgeEnds(room,edge),fraction=distance/length;if(edge.kind==='line')return [a[0]+fraction*(b[0]-a[0]),a[1]+fraction*(b[1]-a[1])];const [cx,cy]=edge.centre,r=Math.hypot(a[0]-cx,a[1]-cy),angle=Math.atan2(a[1]-cy,a[0]-cx)+fraction*edge.sweep;return [cx+r*Math.cos(angle),cy+r*Math.sin(angle)];}
export function signedArea(room,walls){return walls.reduce((sum,w)=>{const e=w.geometry,[a,b]=edgeEnds(room,e);if(e.kind==='line')return sum+(a[0]*b[1]-a[1]*b[0])/2;edgeLength(room,e);const [cx,cy]=e.centre,r=Math.hypot(a[0]-cx,a[1]-cy);return sum+(cx*(b[1]-a[1])-cy*(b[0]-a[0])+r*r*e.sweep)/2;},0);}
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function intersects(a,b,c,d){const on=(p,q,r)=>Math.abs(cross(p,q,r))<=EPS&&r[0]>=Math.min(p[0],q[0])-EPS&&r[0]<=Math.max(p[0],q[0])+EPS&&r[1]>=Math.min(p[1],q[1])-EPS&&r[1]<=Math.max(p[1],q[1])+EPS;const x=cross(a,b,c),y=cross(a,b,d),z=cross(c,d,a),v=cross(c,d,b);return x*y<0&&z*v<0||on(a,b,c)||on(a,b,d)||on(c,d,a)||on(c,d,b);}
export function validateLineTopology(room,walls){
 if(!Array.isArray(room.corners)||room.corners.length<3||room.corners.length>256||walls.length!==room.corners.length)throw new Error('Invalid topology corner count');const ids=new Set();for(const c of room.corners){if(typeof c.id!=='string'||!c.id||ids.has(c.id)||![c.x,c.y].every(Number.isFinite))throw new Error('Invalid/duplicate topology corner');ids.add(c.id);}
 for(let i=0;i<walls.length;i++){const e=walls[i].geometry;if(e?.kind!=='line')throw new Error('Arc room intersection validation is not yet supported');if(e.startCornerId!==room.corners[i].id||e.endCornerId!==room.corners[(i+1)%walls.length].id)throw new Error('Disconnected perimeter edge');const length=edgeLength(room,e);if(length<=EPS||Math.abs(length-walls[i].length.value)>EPS)throw new Error('Perimeter length disagrees with edge geometry');}
 const points=topologyPoints(room);for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++)if(j!==i+1&&!(i===0&&j===points.length-1)&&intersects(points[i],points[(i+1)%points.length],points[j],points[(j+1)%points.length]))throw new Error('Perimeter self-intersects or touches');
 const area=signedArea(room,walls);if(Math.abs(area)<=EPS||!['clockwise','counterclockwise'].includes(room.orientation)||(area<0)!==(room.orientation==='clockwise'))throw new Error('Invalid perimeter area/orientation');return room;
}
