import {unitsWitness} from './units-witness.mjs';
import {assertBuiltCandidate} from './build-subject.mjs';
import {chromium} from 'playwright';
import {serveCandidate} from './static-preview.mjs';
import {candidateIdentity} from './identity.mjs';
import {digest} from './gate.mjs';
import {mkdirSync,readFileSync,writeFileSync,readdirSync,renameSync} from 'node:fs';
import {unzipSync,strFromU8} from 'fflate';
import assert from 'node:assert/strict';
const dir='artifacts/entry';mkdirSync(dir,{recursive:true});const attempt=`${dir}/attempt-${Date.now()}`;mkdirSync(attempt);for(const e of readdirSync(dir,{withFileTypes:true}))if(e.isFile())renameSync(`${dir}/${e.name}`,`${attempt}/${e.name}`);let produced=false;writeFileSync(`${dir}/status.json`,'{"outcome":"running"}');process.on('exit',code=>writeFileSync(`${dir}/status.json`,JSON.stringify({outcome:code===0&&produced?'pass':'fail'})));
const candidate=candidateIdentity();assertBuiltCandidate(candidate);const server=await serveCandidate(candidate),browser=await chromium.launch({args:['--use-angle=swiftshader']}),results=[],errors=[];
const expected=[[0,0],[400,0],[400,200],[200,200],[200,400],[0,400]],segments=[[400,0],[200,90],[200,180],[200,90],[200,180],[400,270]];
try{for(const method of ['preset','draw','perimeter','pointer']){const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(server.url);await page.getByRole('button',{name:method==='preset'?'Preset outline':(method==='draw'||method==='pointer')?'Draw outline':'Wall by wall',exact:true}).click();
 if(method==='draw'){for(let i=0;i<expected.length;i++){await page.getByRole('button',{name:'Add corner',exact:true}).click();await page.getByRole('textbox',{name:`X (cm) · Corner ${i+1}`,exact:true}).fill(String(expected[i][0]));await page.getByRole('textbox',{name:`Y (cm) · Corner ${i+1}`,exact:true}).fill(String(expected[i][1]));}}
 if(method==='pointer'){for(const point of expected){const screen=await page.locator('.draft-plan').evaluate((svg,p)=>{const m=svg.getScreenCTM();return {x:m.a*p[0]-m.c*p[1]+m.e,y:m.b*p[0]-m.d*p[1]+m.f};},point);const visible=await page.locator('.draft-plan').boundingBox(),viewport=page.viewportSize();assert(screen.x>=visible.x&&screen.x<=visible.x+visible.width&&screen.y>=visible.y&&screen.y<=visible.y+visible.height&&screen.x>=0&&screen.x<viewport.width&&screen.y>=0&&screen.y<viewport.height,'Draft point must be inside visible SVG and viewport');await page.touchscreen.tap(screen.x,screen.y);}}
 if(method==='perimeter'){for(let i=3;i<6;i++)await page.getByRole('button',{name:'Add wall',exact:true}).click();for(let i=0;i<6;i++){const wall=String.fromCharCode(65+i);await page.getByRole('textbox',{name:`Length (cm) · ${wall}`,exact:true}).fill(String(segments[i][0]));await page.getByRole('textbox',{name:`Direction (degrees) · ${wall}`,exact:true}).fill(String(segments[i][1]));}}
 await page.getByRole('button',{name:'Preview outline',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'A · 400.00 cm',exact:true}).waitFor();await page.getByRole('button',{name:'3D view',exact:true}).click();await page.locator('.scene canvas').waitFor();await page.screenshot({path:`${dir}/${method}-3d.png`,fullPage:true});
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Save project file',exact:true}).click()]);await download.saveAs(`${dir}/${method}.rumsyn`);const document=JSON.parse(strFromU8(unzipSync(new Uint8Array(readFileSync(`${dir}/${method}.rumsyn`)))['project.json']));assert.equal(document.version,2);const state=document.session.state;assert.equal(state.room.kind,'polygon');assert.equal(state.room.corners.length,6);state.room.corners.forEach((p,i)=>assert(Math.hypot(p.x-expected[i][0],p.y-expected[i][1])<1e-6));assert.equal(state.room.approximate,method!=='perimeter');assert(Math.abs(state.walls.reduce((n,w)=>n+w.length.value,0)-1600)<1e-6);assert.equal(state.room.entry,method==='pointer'?'draw':method);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Preview outline',exact:true}).waitFor();await page.getByRole('button',{name:'Redo',exact:true}).click();await page.getByRole('button',{name:'A · 400.00 cm',exact:true}).waitFor();if(method==='preset'){await page.getByRole('button',{name:'A · 400.00 cm',exact:true}).click();await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByRole('alert').filter({hasText:'No changes requested.'}).waitFor();assert.equal(await page.getByRole('dialog').count(),0);await page.getByRole('textbox',{name:'Length (cm)',exact:true}).fill('410');await page.getByRole('button',{name:'Preview change',exact:true}).click();assert((await page.getByRole('dialog').textContent()).includes('Wall B: 200.00 → 200.25 cm'));assert((await page.getByRole('dialog').textContent()).includes('Wall B: 90.00 → 92.86 °'));await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'2D plan',exact:true}).click();await page.locator('svg text').filter({hasText:'A · 410.00 cm'}).waitFor();await page.getByRole('textbox',{name:'Start corner X (cm)',exact:true}).fill('10');await page.getByRole('textbox',{name:'Start corner Y (cm)',exact:true}).fill('20');await page.getByRole('button',{name:'Preview corner move',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.waitForFunction(el=>el.value==='10.00',await page.getByRole('textbox',{name:'Start corner X (cm)',exact:true}).elementHandle(),{timeout:5000});await page.getByRole('button',{name:'Undo',exact:true}).click();await page.waitForFunction(el=>el.value==='0.00',await page.getByRole('textbox',{name:'Start corner X (cm)',exact:true}).elementHandle(),{timeout:5000});await page.screenshot({path:`${dir}/polygon-refinement.png`,fullPage:true});}results.push({method,outcome:'pass',archiveHash:digest(readFileSync(`${dir}/${method}.rumsyn`)),provenance:state.room.cornersProvenance});await context.close();}
 results.push(await unitsWitness(browser,server.url,dir,errors));
 const after=candidateIdentity();assert.equal(after.sourceDigest,candidate.sourceDigest);assert.equal(after.buildDigest,candidate.buildDigest);assert.equal(errors.length,0,errors.join('\n'));writeFileSync(`${dir}/report.json`,JSON.stringify({candidate,results,errors,browser:browser.version(),physicalDevices:'not_run',limits:'Bounded line-polygon creation/edit/history and measurement controls; consumer constraints/repairs, arcs and physical-device qualification incomplete'},null,2));produced=true;console.log(JSON.stringify(results));}finally{await browser.close();await server.close();}
