import {assertBuiltCandidate} from './build-subject.mjs';
import {serveCandidate} from './static-preview.mjs';
import {chromium} from 'playwright';
import {mkdirSync,writeFileSync,readFileSync,readdirSync,renameSync} from 'node:fs';
import {unzipSync,zipSync,strFromU8,strToU8} from 'fflate';
import assert from 'node:assert/strict';
import {candidateIdentity} from './identity.mjs';
import {digest} from './gate.mjs';
const remotePlugin=process.env.RUMSYN_REMOTE_PLUGIN==='1';const dir=remotePlugin?'artifacts/workflow-public':'artifacts/workflow';mkdirSync(dir,{recursive:true});const attempt=`${dir}/attempt-${Date.now()}`;mkdirSync(attempt,{recursive:true});for(const e of readdirSync(dir,{withFileTypes:true}))if(e.isFile())renameSync(`${dir}/${e.name}`,`${attempt}/${e.name}`);
let produced=false;writeFileSync(`${dir}/status.json`,JSON.stringify({outcome:'running'}));process.on('exit',code=>writeFileSync(`${dir}/status.json`,JSON.stringify({outcome:code===0&&produced?'pass':'fail'})));
const candidate=candidateIdentity();assertBuiltCandidate(candidate);if(!candidate.buildFiles.length)throw new Error('Build artifact absent');
const preview=await serveCandidate(candidate);const url=preview.url;const browser=await chromium.launch({args:['--use-angle=swiftshader']});
const failures=[],steps=[],remoteResources=[],remoteReads=[];const step=(id,details={})=>{steps.push({id,outcome:'pass',...details});writeFileSync(`${dir}/progress.json`,JSON.stringify({candidate,steps},null,2));};
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>failures.push(e.message));if(remotePlugin)page.on('response',response=>{const u=new URL(response.url());if(['api.github.com','raw.githubusercontent.com','yaniv-golan.github.io'].includes(u.hostname))remoteReads.push((async()=>{const bytes=await response.body();remoteResources.push({url:response.url(),status:response.status(),sha256:digest(bytes),bytes:bytes.length,accessControlAllowOrigin:response.headers()['access-control-allow-origin']??null});})());});await page.goto(new URL('catalog/manifest.json',url).href);await page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('rumsyn-m1',1);request.onupgradeneeded=()=>{request.result.createObjectStore('recovery',{keyPath:'id'});request.result.createObjectStore('library',{keyPath:'identity'});};request.onsuccess=()=>{request.result.close();resolve();};request.onerror=()=>reject(request.error);}));await page.goto(url);step('local-database-v1-to-v2-upgrade');
 await page.getByRole('heading',{name:'Create a measured room'}).waitFor();await page.screenshot({path:`${dir}/empty.png`,fullPage:true});step('empty-start');
 for(const [id,value]of Object.entries({A:400,B:300,C:350,D:300}))await page.getByRole('textbox',{name:`Wall ${id} (cm)`,exact:true}).fill(String(value));
 await page.getByRole('textbox',{name:'Diagonal A-C (cm)',exact:true}).fill('450');await page.getByLabel('Known clockwise orientation').selectOption('clockwise');await page.getByRole('button',{name:'Preview room',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'A · 400.00 cm',exact:true}).waitFor();step('create-irregular-room');
 await page.getByRole('button',{name:'A · 400.00 cm',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Selected object');step('keyboard-selection-opens-focused-properties');await page.getByRole('textbox',{name:'Length (cm)',exact:true}).fill('410');await page.getByRole('button',{name:'Preview change',exact:true}).click();assert((await page.getByRole('dialog').textContent()).includes('400.00 → 410.00'));await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.locator('svg text').filter({hasText:'A · 400.00 cm'}).waitFor();step('dimension-cancel');
 await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.locator('svg text').filter({hasText:'A · 410.00 cm'}).waitFor();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.locator('svg text').filter({hasText:'A · 400.00 cm'}).waitFor();await page.getByRole('button',{name:'Redo',exact:true}).click();await page.locator('svg text').filter({hasText:'A · 410.00 cm'}).waitFor();step('dimension-apply-undo-redo');
 const properties=page.locator('section').filter({has:page.getByRole('heading',{name:'Selected object',exact:true})});
 await properties.getByRole('button',{name:'Preview placement',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();
 await properties.getByRole('textbox',{name:'Offset from wall start (cm)',exact:true}).fill('220');await properties.getByRole('textbox',{name:'Width (cm)',exact:true}).fill('80');await properties.getByRole('button',{name:'Preview placement',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal(await page.locator('svg line title').count(),2);step('two-opening-plan');
 await page.getByRole('button',{name:'3D view',exact:true}).click();await page.locator('.scene canvas').waitFor();await page.screenshot({path:`${dir}/room-3d.png`,fullPage:true});step('three-dimensional-view',{gpu:'Chromium SwiftShader desktop proxy; not physical-device evidence'});
 const faded=await page.locator('.scene canvas').screenshot();await page.getByRole('button',{name:'Show solid walls',exact:true}).click();const solid=await page.locator('.scene canvas').screenshot();assert.notEqual(digest(faded),digest(solid));await page.getByRole('button',{name:'Fade near walls',exact:true}).click();await page.getByRole('button',{name:'Fit / reset view',exact:true}).click();await page.screenshot({path:`${dir}/near-wall-fade.png`,fullPage:true});step('reversible-wall-fade-fit-view');
 await page.getByRole('button',{name:'Room',exact:true}).click();await page.getByRole('button',{name:'A · 410.00 cm',exact:true}).click();await page.getByRole('textbox',{name:'Length (cm)',exact:true}).fill('420');await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.waitForFunction(el=>el.value==='420.00',await page.getByRole('textbox',{name:'Length (cm)',exact:true}).elementHandle(),{timeout:5000});step('dimension-edit-from-3d');
 await page.getByRole('button',{name:'Furniture',exact:true}).click();
 const generic=page.locator('section').filter({has:page.getByRole('heading',{name:'Generic furniture',exact:true})});await generic.getByRole('textbox',{name:'X (cm)',exact:true}).fill('150');await generic.getByRole('textbox',{name:'Y (cm)',exact:true}).fill('0');await generic.getByRole('button',{name:'Preview placement',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();step('generic-placement');
 await page.getByRole('textbox',{name:'Product URL',exact:true}).fill('https://www.ikea.com/il/he/p/lack-side-table-white-30449908/');await page.getByRole('button',{name:'Add from URL',exact:true}).click();await page.locator('.product-card').waitFor();assert((await page.locator('.product-card').textContent()).includes('55.00 cm × 55.00 cm × 45.00 cm'));await page.getByRole('button',{name:'Place in room',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'Room',exact:true}).click();await page.getByRole('button',{name:'LACK שולחן צד',exact:true}).waitFor();await page.getByRole('button',{name:'Furniture',exact:true}).click();step('ikea-seed-through-plugin-path');
 const manifest=JSON.parse(readFileSync('producer-seed/rum-plugin.json')),catalog=readFileSync('producer-seed/data/seed-2026-10-08/catalog.json'),commit='a'.repeat(40);const repoApi='https://api.github.com/repos/yaniv-golan/RUMSYN-ikea-israel';
 if(!remotePlugin){await page.route(repoApi,route=>route.fulfill({json:{private:false,default_branch:'main'}}));await page.route(`${repoApi}/commits/main`,route=>route.fulfill({json:{sha:commit}}));await page.route(`https://raw.githubusercontent.com/yaniv-golan/RUMSYN-ikea-israel/${commit}/rum-plugin.json`,route=>route.fulfill({json:manifest}));await page.route(manifest.catalog.url,route=>route.fulfill({body:catalog,contentType:'application/json'}));}
 await page.getByRole('button',{name:'Review repository',exact:true}).click();await page.getByRole('heading',{name:'Review plugin before installing',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Remove plugin',exact:true}).count(),0);await page.getByRole('button',{name:'Install reviewed plugin',exact:true}).click();await page.getByRole('button',{name:'Remove plugin',exact:true}).waitFor();await page.getByRole('button',{name:'Add from URL',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Place in room',exact:true}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'Remove plugin',exact:true}).click();assert.equal(await page.locator('.product-card').filter({has:page.getByRole('button',{name:'Place in room',exact:true})}).count(),1);await page.getByRole('button',{name:'Room',exact:true}).click();await page.getByRole('button',{name:'LACK שולחן צד',exact:true}).waitFor();step(remotePlugin?'public-plugin-review-install-remove-preserves-products':'fixture-plugin-review-install-remove-preserves-products',{network:remotePlugin?'Real browser cross-origin public GitHub metadata, pinned raw manifest and versioned Pages catalog':'intercepted fixtures; not public CORS evidence'});
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Save project file',exact:true}).click()]);await download.saveAs(`${dir}/room.rumsyn`);const archive=readFileSync(`${dir}/room.rumsyn`);const saved=JSON.parse(strFromU8(unzipSync(new Uint8Array(archive))['project.json']));assert.equal(saved.session.state.furniture.find(f=>f.product)?.product.plugin.repository,'https://github.com/yaniv-golan/RUMSYN-ikea-israel');step('portable-save',{bytes:archive.byteLength,sha256:digest(archive)});
 await page.getByLabel('Language').selectOption('he');await page.getByRole('button',{name:'תצוגה תלת־ממד',exact:true}).waitFor();assert.equal(await page.locator('html').getAttribute('dir'),'rtl');await page.screenshot({path:`${dir}/hebrew.png`,fullPage:true});step('hebrew-controls');
 const fresh=await browser.newContext({viewport:{width:1440,height:1000}}),recipient=await fresh.newPage();recipient.on('pageerror',e=>failures.push(e.message));await recipient.goto(url);await recipient.getByRole('heading',{name:'Create a measured room'}).waitFor();await recipient.getByLabel('Open project file',{exact:true}).setInputFiles(`${dir}/room.rumsyn`);await recipient.getByRole('button',{name:'LACK שולחן צד',exact:true}).waitFor();assert.equal(await recipient.locator('.product-card').count(),0);await recipient.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await recipient.getByRole('button',{name:'LACK שולחן צד',exact:true}).count(),0);await recipient.getByRole('button',{name:'Redo',exact:true}).click();await recipient.getByRole('button',{name:'LACK שולחן צד',exact:true}).waitFor();step('fresh-profile-open-history-no-library-pollution');
 const corrupt=JSON.parse(strFromU8(unzipSync(new Uint8Array(archive))['project.json']));corrupt.session.state.room.diagonal.value=1;writeFileSync(`${dir}/malformed.rumsyn`,zipSync({'project.json':strToU8(JSON.stringify(corrupt))}));await recipient.getByLabel('Open project file',{exact:true}).setInputFiles(`${dir}/malformed.rumsyn`);await recipient.getByRole('alert').waitFor();assert((await recipient.getByRole('alert').textContent()).includes('diagonal'));await recipient.getByRole('button',{name:'A · 420.00 cm',exact:true}).waitFor();step('malformed-open-preserves-session');
 await recipient.screenshot({path:`${dir}/recipient.png`,fullPage:true});
 const touch=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true}),tablet=await touch.newPage();tablet.on('pageerror',e=>failures.push(e.message));await tablet.goto(url);await tablet.getByLabel('Open project file',{exact:true}).setInputFiles(`${dir}/room.rumsyn`);await tablet.getByRole('button',{name:'LACK שולחן צד',exact:true}).tap();await tablet.getByRole('heading',{name:'Selected object',exact:true}).waitFor();assert.equal(await tablet.getByRole('textbox',{name:'Width (cm)',exact:true}).count(),0);await tablet.getByRole('button',{name:'3D view',exact:true}).tap();await tablet.locator('.scene canvas').waitFor();await tablet.getByRole('button',{name:'Zoom in',exact:true}).tap();await tablet.getByRole('button',{name:'Zoom out',exact:true}).tap();await tablet.getByRole('button',{name:'Fit / reset view',exact:true}).tap();await tablet.getByLabel('Language').selectOption('he');const side=await tablet.locator('.sidebar').boundingBox(),scene=await tablet.locator('.canvas-wrap').boundingBox();assert(side.x>scene.x);assert(scene.width>500);await tablet.screenshot({path:`${dir}/tablet-rtl-proxy.png`,fullPage:true});step('touch-rtl-contextual-panel-proxy',{device:'1024x768 Chromium touch emulation; physical tablet not_run'});await touch.close();
 const narrow=await browser.newContext({viewport:{width:637,height:810},hasTouch:true}),phone=await narrow.newPage();await phone.goto(url);await phone.getByLabel('Open project file',{exact:true}).setInputFiles(`${dir}/room.rumsyn`);const wallLabel=phone.locator('svg text').filter({hasText:'A · 420.00 cm'});await wallLabel.scrollIntoViewIfNeeded();const scrollBefore=await phone.evaluate(()=>scrollY);await wallLabel.tap();await phone.getByRole('heading',{name:'Selected object',exact:true}).waitFor();assert(Math.abs((await phone.evaluate(()=>scrollY))-scrollBefore)<2);await phone.screenshot({path:`${dir}/narrow-selection.png`,fullPage:true});step('narrow-pointer-selection-does-not-scroll-scene',{viewport:'637x810 browser proxy; physical phone not_run'});await narrow.close();
 const legacyBaseline=JSON.parse(readFileSync('tests/fixtures/v1/v1-behavior-baseline.json'));for(const witness of legacyBaseline.cases){await recipient.getByLabel('Open project file',{exact:true}).setInputFiles(`tests/fixtures/v1/${witness.file}`);await recipient.getByText('Project upgraded to format2; original file unchanged. Saving writes format2, which older RUMSYN versions cannot open.',{exact:true}).waitFor();const [legacySave]=await Promise.all([recipient.waitForEvent('download'),recipient.getByRole('button',{name:'Save project file',exact:true}).click()]);const path=`${dir}/upgraded-${witness.file}`;await legacySave.saveAs(path);const opened=JSON.parse(strFromU8(unzipSync(new Uint8Array(readFileSync(path)))['project.json']));assert.equal(opened.version,2);assert.equal(opened.session.cursor,witness.cursor);assert.equal(opened.session.history.length,7);assert.equal(digest(readFileSync(`tests/fixtures/v1/${witness.file}`)),witness.sha256);}step('actual-historical-v1-open-notice-save-v2-six-cursors');
 const recoveryWitness=legacyBaseline.cases.find(w=>w.cursor===3),legacyDocument=JSON.parse(strFromU8(unzipSync(new Uint8Array(readFileSync(`tests/fixtures/v1/${recoveryWitness.file}`)))['project.json']));
 for(const corruptRecovery of [false,true]){const recoveredContext=await browser.newContext(),recoveredPage=await recoveredContext.newPage(),document=structuredClone(legacyDocument);if(corruptRecovery)document.session.state.room.diagonal.value=1;await recoveredPage.goto(new URL('catalog/manifest.json',url).href);await recoveredPage.evaluate(document=>new Promise((resolve,reject)=>{const request=indexedDB.open('rumsyn-m1',1);request.onupgradeneeded=()=>{request.result.createObjectStore('recovery',{keyPath:'id'});request.result.createObjectStore('library',{keyPath:'identity'});};request.onsuccess=()=>{const database=request.result,tx=database.transaction('recovery','readwrite');tx.objectStore('recovery').put({id:'current',document});tx.oncomplete=()=>{database.close();resolve();};tx.onerror=()=>reject(tx.error);};request.onerror=()=>reject(request.error);}),document);await recoveredPage.goto(url);
  if(corruptRecovery){await recoveredPage.getByRole('alert').waitFor();const unchanged=await recoveredPage.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('rumsyn-m1');request.onsuccess=()=>{const database=request.result,get=database.transaction('recovery').objectStore('recovery').get('current');get.onsuccess=()=>{database.close();resolve(get.result.document);};get.onerror=()=>reject(get.error);};request.onerror=()=>reject(request.error);}));assert.deepEqual(unchanged,document);step('failed-recovery-migration-preserves-prior-document');}
  else{await recoveredPage.getByText('Project upgraded to format2; original file unchanged. Saving writes format2, which older RUMSYN versions cannot open.',{exact:true}).waitFor();await recoveredPage.waitForFunction(()=>new Promise(resolve=>{const request=indexedDB.open('rumsyn-m1');request.onsuccess=()=>{const database=request.result,get=database.transaction('recovery').objectStore('recovery').get('current');get.onsuccess=()=>{database.close();resolve(get.result?.document.version===2&&get.result.document.session.history.length===7);};};}));step('valid-recovery-v1-migrates-full-history-with-notice');}await recoveredContext.close();}
 await Promise.all(remoteReads);if(remotePlugin){assert(remoteResources.some(r=>r.url===manifest.catalog.url&&r.status===200&&r.sha256===manifest.catalog.sha256));assert(remoteResources.some(r=>r.url.endsWith('/rum-plugin.json')&&r.status===200));}
 const after=candidateIdentity();assert.equal(after.sourceDigest,candidate.sourceDigest);assert.equal(after.buildDigest,candidate.buildDigest);assert.equal(failures.length,0,failures.join('\n'));
 writeFileSync(`${dir}/report.json`,JSON.stringify({candidate,node:process.version,browser:browser.version(),url,command:'pnpm test:workflow',steps,failures,remoteResources,physicalDevices:'not_run'},null,2));produced=true;console.log(JSON.stringify({steps:steps.length,browser:browser.version(),failures},null,2));await fresh.close();await context.close();
}finally{await browser.close();await preview.close();}
