import {test,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {inspectRepository,repositoryIdentity,validatePlugin,fetchBounded,catalogFromInstalled} from '../../packages/plugins/index.js';
import {sha256,validateCatalog} from '../../packages/catalog/index.js';
const manifest=JSON.parse(readFileSync('producer-seed/rum-plugin.json')),catalogBytes=readFileSync('producer-seed/data/seed-2026-10-08/catalog.json'),commit='a'.repeat(40);
function mock({badBytes=false,redirect=false}={}){const calls=[];return {calls,fetcher:async(url,options)=>{calls.push({url,options});let body;if(url.endsWith('/RUMSYN-ikea-israel'))body=JSON.stringify({private:false,default_branch:'main'});else if(url.includes('/commits/'))body=JSON.stringify({sha:commit});else if(url.endsWith('/rum-plugin.json'))body=JSON.stringify(manifest);else body=badBytes?'{}':catalogBytes;const response=new Response(body,{status:200});if(redirect)Object.defineProperty(response,'redirected',{value:true});return response;}};}
test('M1 R024 R025: commit-pinned repository preview verifies versioned bytes before installation',async()=>{const m=mock(),candidate=await inspectRepository('https://github.com/yaniv-golan/RUMSYN-ikea-israel',{fetcher:m.fetcher});expect(candidate.commit).toBe(commit);expect(m.calls[2].url).toContain(`/${commit}/rum-plugin.json`);expect(m.calls.every(c=>c.options.redirect==='error'&&c.options.credentials==='omit')).toBe(true);expect((await catalogFromInstalled(candidate)).record.products[0].dimensions.width).toBe(55);});
test('M1 R025 R033: changed bytes and corrupt cache reject rather than replace source facts',async()=>{await expect(inspectRepository('https://github.com/yaniv-golan/RUMSYN-ikea-israel',{fetcher:mock({badBytes:true}).fetcher})).rejects.toThrow('hash mismatch');const candidate=await inspectRepository('https://github.com/yaniv-golan/RUMSYN-ikea-israel',{fetcher:mock().fetcher});candidate.catalogText+=' ';await expect(catalogFromInstalled(candidate)).rejects.toThrow('cache hash');});
test('M1 R024 R033: origins redirects size and unsupported contracts reject',async()=>{expect(()=>repositoryIdentity('https://github.com/a/b/tree/main')).toThrow('repository');const bad=structuredClone(manifest);bad.origins=['https://attacker.example'];expect(()=>validatePlugin(bad,'yaniv-golan')).toThrow('origin');const version=structuredClone(manifest);version.contractVersion=2;expect(()=>validatePlugin(version,'yaniv-golan')).toThrow('contract');await expect(fetchBounded('https://example.test',4,async()=>new Response('12345'))).rejects.toThrow('size limit');await expect(inspectRepository('https://github.com/yaniv-golan/RUMSYN-ikea-israel',{fetcher:mock({redirect:true}).fetcher})).rejects.toThrow('redirected');});
test('M1 R025 R027: unsafe source URLs duplicate identities and wrong country records reject',()=>{const source=JSON.parse(catalogBytes),bad=structuredClone(source);bad.products[0].sourceUrl='javascript:alert(1)';expect(()=>validateCatalog(bad)).toThrow('identity');const duplicate=structuredClone(source);duplicate.products.push(duplicate.products[0]);expect(()=>validateCatalog(duplicate)).toThrow('identity');const country=structuredClone(source);country.country='US';expect(()=>validateCatalog(country)).toThrow('malformed');});

test('M1 R025 manager cache witness: mutated manifest/catalog pair cannot reuse published manifest identity',async()=>{const candidate=await inspectRepository('https://github.com/yaniv-golan/RUMSYN-ikea-israel',{fetcher:mock().fetcher});const catalog=JSON.parse(candidate.catalogText);catalog.products[0].dimensions.width=100;candidate.catalogText=JSON.stringify(catalog);candidate.manifest.catalog.sha256=await sha256(new TextEncoder().encode(candidate.catalogText));await expect(catalogFromInstalled(candidate)).rejects.toThrow('Manifest cache disagrees');candidate.manifestText=JSON.stringify(candidate.manifest);await expect(catalogFromInstalled(candidate)).rejects.toThrow('Manifest cache hash');});
