import {test,expect} from 'vitest';
import {edgeLength,pointAtEdge,signedArea,validateLineTopology} from '../../packages/model/topology.js';
import {CommandSession} from '../../packages/commands/index.js';
import {polygonRoom,perimeterPoints,emptyProject,roomPoints} from '../../packages/model/room.js';
import {importProject,exportProject} from '../../packages/persistence/index.js';
import {footprintOutsideArea,insideRoom,placementWarnings} from '../../packages/geometry/placement.js';
import {parseLength} from '../../packages/model/index.js';
function outline(points){const room={corners:points.map(([x,y],i)=>({id:`c${i}`,x,y})),orientation:'counterclockwise'},walls=points.map((p,i)=>({id:`w${i}`,geometry:{kind:'line',startCornerId:`c${i}`,endCornerId:`c${(i+1)%points.length}`}}));for(const w of walls)w.length={value:edgeLength(room,w.geometry),unit:'cm',source:'derived'};return {room,walls};}
test('M2 R005: concave L topology has analytical area perimeter and rejects crossed outlines',()=>{const state=outline([[0,0],[400,0],[400,200],[200,200],[200,400],[0,400]]);expect(validateLineTopology(state.room,state.walls)).toBe(state.room);expect(signedArea(state.room,state.walls)).toBe(120000);expect(state.walls.reduce((n,w)=>n+w.length.value,0)).toBe(1600);const crossed=outline([[0,0],[100,100],[0,100],[100,0]]);expect(()=>validateLineTopology(crossed.room,crossed.walls)).toThrow('self-intersects');});
test('M2 R005 R012: analytic quarter arc and reversed host offsets retain exact geometry',()=>{const room={corners:[{id:'a',x:100,y:0},{id:'b',x:0,y:100}]},arc={kind:'arc',startCornerId:'a',endCornerId:'b',centre:[0,0],sweep:Math.PI/2},reverse={...arc,startCornerId:'b',endCornerId:'a',sweep:-arc.sweep};expect(edgeLength(room,arc)).toBeCloseTo(50*Math.PI,10);expect(edgeLength(room,reverse)).toBeCloseTo(50*Math.PI,10);for(const distance of [0,25,50*Math.PI]){const p=pointAtEdge(room,arc,distance),q=pointAtEdge(room,reverse,edgeLength(room,arc)-distance);expect(p[0]).toBeCloseTo(q[0],8);expect(p[1]).toBeCloseTo(q[1],8);}expect(()=>pointAtEdge(room,arc,-1)).toThrow('offset');});
test('M2 R009: explicit imperial length uses canonical centimeters without display rounding',()=>{expect(parseLength('100 in')).toBe(254);expect(parseLength('1.64 m')).toBe(164);});

test('M2 R004 R005: shared polygon command creates concave geometry with portable executable history',()=>{const s=new CommandSession(emptyProject('synthetic-L')),points=[[0,0],[400,0],[400,200],[200,200],[200,400],[0,400]],preview=s.previewOutline({points,entry:'draw'});expect(s.state.room).toBeNull();s.apply(preview.id);expect(s.state.room.approximate).toBe(true);expect(roomPoints(s.state)).toEqual(points);expect(signedArea(s.state.room,s.state.walls)).toBe(120000);const opened=importProject(exportProject(s));opened.undo();expect(opened.state.room).toBeNull();opened.redo();expect(roomPoints(opened.state)).toEqual(points);expect(()=>s.previewWallLength('wall-1',410)).toThrow('corner/constraint');expect(roomPoints(s.state)).toEqual(points);});
test('M2 R013 manager concave witness: inside arms pass but a footprint bridging an outside notch warns',()=>{const L=[[0,0],[400,0],[400,200],[200,200],[200,400],[0,400]];expect(insideRoom(L,[300,100])).toBe(true);expect(insideRoom(L,[300,300])).toBe(false);const U=[[0,0],[400,0],[400,400],[300,400],[300,100],[100,100],[100,400],[0,400]],state={room:{vertices:U},furniture:[]},item={width:300,depth:100,height:75,x:200,y:250,elevation:0,rotation:0};for(const point of [[50,200],[350,200],[350,300],[50,300]])expect(insideRoom(U,point)).toBe(true);expect(placementWarnings(state,item)).toContain('Furniture footprint extends outside the room.');});

test('M2 R013 manager coincident-edge witness: enclosing notch reports exact outside area while boundary contact fits',()=>{const U=[[0,0],[400,0],[400,400],[300,400],[300,100],[100,100],[100,400],[0,400]],room={room:{vertices:U},furniture:[]},enclosing={width:400,depth:400,height:75,x:200,y:200,elevation:0,rotation:0};expect(footprintOutsideArea(U,enclosing)).toBe(60000);expect(placementWarnings(room,enclosing)).toContain('Furniture footprint extends outside the room.');const arm={...enclosing,width:100,depth:400,x:50};expect(footprintOutsideArea(U,arm)).toBe(0);expect(placementWarnings(room,arm)).toEqual([]);});

test('M2 R004 R009 R010: perimeter lengths need complete entered directions and preserve contradiction',()=>{const segments=[{length:400,direction:0},{length:200,direction:90},{length:200,direction:180},{length:200,direction:90},{length:200,direction:180},{length:400,direction:270}],points=perimeterPoints(segments),created=polygonRoom({entry:'perimeter',segments});expect(points.length).toBe(6);expect(signedArea(created.room,created.walls)).toBeCloseTo(120000,6);expect(created.walls.every(w=>w.length.source==='entered')).toBe(true);expect(created.room.perimeterMeasurements).toEqual(segments);expect(created.room.approximate).toBe(false);expect(()=>polygonRoom({entry:'perimeter',points})).toThrow('three walls');const partial=structuredClone(segments);delete partial[3].direction;expect(()=>polygonRoom({entry:'perimeter',segments:partial})).toThrow('insufficient');const bad=structuredClone(segments);bad[0].length=401;expect(()=>perimeterPoints(bad)).toThrow('residual 1.00');expect(bad[0].length).toBe(401);});

test('M2 R033: persisted perimeter lengths and directions cannot contradict canonical topology',()=>{const segments=[{length:400,direction:0},{length:300,direction:90},{length:400,direction:180},{length:300,direction:270}],session=new CommandSession(emptyProject('synthetic-perimeter'));session.apply(session.previewOutline({entry:'perimeter',segments}).id);const before=session.serialize(),d=JSON.parse(before);d.state.room.perimeterMeasurements[0].length=999;expect(()=>CommandSession.reopen(JSON.stringify(d))).toThrow('residual');const e=JSON.parse(before);e.history[0].after.room.perimeterMeasurements[1].direction=45;expect(()=>CommandSession.reopen(JSON.stringify(e))).toThrow('residual');expect(session.serialize()).toBe(before);});
